' <auto-generated />
Imports System
Imports DataService
Imports Microsoft.EntityFrameworkCore
Imports Microsoft.EntityFrameworkCore.Infrastructure
Imports Microsoft.EntityFrameworkCore.Metadata
Imports Microsoft.EntityFrameworkCore.Migrations
Imports Microsoft.EntityFrameworkCore.Storage.ValueConversion

Namespace DataService.Migrations

    <DbContext(GetType(DataService.DataServiceDbContext))>
    <Migration("20240820133246_OrderItem")>
    Partial Class OrderItem

        ''' <inheritdoc/> 
        Protected Overrides Sub BuildTargetModel(ByVal modelBuilder As ModelBuilder)
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8").HasAnnotation("Relational:MaxIdentifierLength", 128)
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder)
            modelBuilder.Entity("DataService.OrderItem", Function(b)
                b.[Property](Of Integer)("Id").ValueGeneratedOnAdd().HasColumnType("int")
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.[Property](Of Integer)("Id"))
                b.[Property](Of Single)("Discount").HasColumnType("real")
                b.[Property](Of DateTime)("OrderDate").HasColumnType("datetime2")
                b.[Property](Of String)("ProductName").IsRequired().HasColumnType("nvarchar(max)")
                b.[Property](Of Integer)("Quantity").HasColumnType("int")
                b.[Property](Of Decimal)("UnitPrice").HasColumnType("decimal(18,2)")
                b.HasKey("Id")
                b.ToTable("OrderItems")
            End Function)
        End Sub
    End Class
End Namespace
